name: Build

on: 
  push:
    branches: [ master ]

jobs:
  docker:
    name: Docker image test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      if: ${{ github.repository_owner == 'ShinyColorsWiki' && github.ref == 'refs/heads/master' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build a multi-platform docker image and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: |
          ghcr.io/shinycolorswiki/varnish:latest
          type=local,src=/tmp/.buildx-cache
        cache-to: mode=max,type=inline
        load: false
        no-cache: ${{ contains(github.event.head_commit.message, '[no cache]') }}
        push: ${{ github.repository_owner == 'ShinyColorsWiki' && github.ref == 'refs/heads/master' }}
        tags: |
          ghcr.io/shinycolorswiki/varnish:latest
          ghcr.io/shinycolorswiki/varnish:${{ github.sha }}
